### ISSUE TITLE
Missing folder/files (?)

### ISSUE THREAD

**Issue by wimvdc** [njbmartin/chroma.js#8]
The README suggest there is an 'example' folder.
> Afterwards you can start the example by executing the following in the example folder:

However there doesn't seem to be such a folder (at least not in the master branch).

**Comment by WolfspiritM** [comment]
Thanks!

We removed the examples from this project to create a new examples project but somehow missed to set it up. This project has been stale for a while however I've been working on a new version which is not yet available on github. (I'll push it on here including examples as soon as I think it's stable)

For now you can take a look here:
http://gamedog.chromatin.eu/chromajs/

And here is a node example:
https://gist.github.com/WolfspiritM/2748bc547c9553ad6c1698a981d7c206

If you need some help and informations feel free to join #developers on our Discord if you have questions:
https://insider.razerzone.com/index.php?threads/come-join-us-on-discord.25768/

**Comment by wimvdc** [comment]
Thanks, the example you provided works excellent!
